workflows:
  flutter-build:
    name: Flutter Build
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: "2.7.0"
        DART_VERSION: "2.10.4"
    scripts:
      - name: Set up Flutter SDK
        script: |
          git clone https://github.com/flutter/flutter.git -b stable
          cd flutter
          git checkout tags/2.7.0 # Usa la versión 2.7.0 del SDK
          export PATH="$PWD/bin:$PATH"
          flutter doctor
      - name: Install dependencies
        script: flutter pub get
      - name: Build the app for Android
        script: flutter build apk --release
      # Si necesitas compilar para iOS también, agrega este bloque:
      - name: Build the app for iOS
        script: flutter build ios --release
