workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60 # Duración máxima en minutos
    instances:
      - macos  # Especifica el tipo de instancia para el build (macos, linux, etc.)
    environment:
      flutter: stable  # Usa la versión estable de Flutter
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build app for iOS
        script: |
          flutter build ios --release
      - name: Build app for Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk # Define los archivos que quieres que Codemagic guarde como artefactos
      - build/ios/iphoneos/Runner.app # Ejemplo para iOS
    publish:
      scripts:
        - name: Publish to Firebase App Distribution
          script: |
            firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app <firebase-app-id>
