workflows:
  flutter-build:
    name: Flutter Build
    environment:
      flutter: stable
    scripts:
      - name: Set up Flutter SDK version 2.7.0
        script: |
          git clone https://github.com/flutter/flutter.git -b stable
          cd flutter
          git checkout tags/2.7.0 # Asegura que se use la versión 2.7.0
          export PATH="$PWD/bin:$PATH"
          flutter doctor
      - name: Install dependencies
        script: flutter pub get
      - name: Build the app for Android
        script: flutter build apk --release
      - name: Build the app for iOS
        script: flutter build ios --release