name: Build Flutter iOS

on:
  push:
    branches:
      - main  # o tu rama principal

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS app
      run: flutter build ios --release --no-codesign

    - name: Archive iOS build
      run: |
        mkdir -p build/ios/ipa
        xcrun -sdk iphoneos -archivePath build/ios/ipa/MyApp.xcarchive flutter build ios --release --no-codesign
        xcrun -sdk iphoneos -exportArchive -archivePath build/ios/ipa/MyApp.xcarchive -exportPath build/ios/ipa
